var classsaklient_1_1errors_1_1httphttpversionnotsupportedexception_1_1_http_http_version_not_supported_exception =
[
    [ "__init__", "classsaklient_1_1errors_1_1httphttpversionnotsupportedexception_1_1_http_http_version_not_supported_exception.html#ab931dad23d1c86e14ea23ab2ee030af1", null ]
];