var hierarchy =
[
    [ "saklient.cloud.api.API", "classsaklient_1_1cloud_1_1api_1_1_a_p_i.html", null ],
    [ "saklient.cloud.client.Client", "classsaklient_1_1cloud_1_1client_1_1_client.html", null ],
    [ "saklient.cloud.resources.diskconfig.DiskConfig", "classsaklient_1_1cloud_1_1resources_1_1diskconfig_1_1_disk_config.html", null ],
    [ "saklient.cloud.enums.eapplianceclass.EApplianceClass", "classsaklient_1_1cloud_1_1enums_1_1eapplianceclass_1_1_e_appliance_class.html", null ],
    [ "saklient.cloud.enums.eavailability.EAvailability", "classsaklient_1_1cloud_1_1enums_1_1eavailability_1_1_e_availability.html", null ],
    [ "saklient.cloud.enums.ediskconnection.EDiskConnection", "classsaklient_1_1cloud_1_1enums_1_1ediskconnection_1_1_e_disk_connection.html", null ],
    [ "saklient.cloud.enums.escope.EScope", "classsaklient_1_1cloud_1_1enums_1_1escope_1_1_e_scope.html", null ],
    [ "saklient.cloud.enums.escriptclass.EScriptClass", "classsaklient_1_1cloud_1_1enums_1_1escriptclass_1_1_e_script_class.html", null ],
    [ "saklient.cloud.enums.eserverinstancestatus.EServerInstanceStatus", "classsaklient_1_1cloud_1_1enums_1_1eserverinstancestatus_1_1_e_server_instance_status.html", null ],
    [ "saklient.cloud.enums.estorageclass.EStorageClass", "classsaklient_1_1cloud_1_1enums_1_1estorageclass_1_1_e_storage_class.html", null ],
    [ "Exception", null, [
      [ "saklient.errors.httpexception.HttpException", "classsaklient_1_1errors_1_1httpexception_1_1_http_exception.html", null ],
      [ "saklient.errors.saklientexception.SaklientException", "classsaklient_1_1errors_1_1saklientexception_1_1_saklient_exception.html", null ]
    ] ],
    [ "saklient.errors.exceptionfactory.ExceptionFactory", "classsaklient_1_1errors_1_1exceptionfactory_1_1_exception_factory.html", null ],
    [ "saklient.cloud.facility.Facility", "classsaklient_1_1cloud_1_1facility_1_1_facility.html", null ],
    [ "saklient.cloud.resources.ftpinfo.FtpInfo", "classsaklient_1_1cloud_1_1resources_1_1ftpinfo_1_1_ftp_info.html", null ],
    [ "saklient.cloud.resources.lbserver.LbServer", "classsaklient_1_1cloud_1_1resources_1_1lbserver_1_1_lb_server.html", null ],
    [ "saklient.cloud.resources.lbvirtualip.LbVirtualIp", "classsaklient_1_1cloud_1_1resources_1_1lbvirtualip_1_1_lb_virtual_ip.html", null ],
    [ "saklient.cloud.models.model.Model", "classsaklient_1_1cloud_1_1models_1_1model_1_1_model.html", null ],
    [ "saklient.cloud.product.Product", "classsaklient_1_1cloud_1_1product_1_1_product.html", null ],
    [ "saklient.cloud.models.queryparams.QueryParams", "classsaklient_1_1cloud_1_1models_1_1queryparams_1_1_query_params.html", null ],
    [ "saklient.cloud.resources.resource.Resource", "classsaklient_1_1cloud_1_1resources_1_1resource_1_1_resource.html", null ],
    [ "saklient.util.Util", "classsaklient_1_1util_1_1_util.html", null ],
    [ "Appliance", null, [
      [ "saklient.cloud.resources.loadbalancer.LoadBalancer", "classsaklient_1_1cloud_1_1resources_1_1loadbalancer_1_1_load_balancer.html", null ],
      [ "saklient.cloud.resources.vpcrouter.VpcRouter", "classsaklient_1_1cloud_1_1resources_1_1vpcrouter_1_1_vpc_router.html", null ]
    ] ],
    [ "HttpBadRequestException", null, [
      [ "saklient.cloud.errors.accountnotfoundexception.AccountNotFoundException", "classsaklient_1_1cloud_1_1errors_1_1accountnotfoundexception_1_1_account_not_found_exception.html", null ],
      [ "saklient.cloud.errors.ambiguouszoneexception.AmbiguousZoneException", "classsaklient_1_1cloud_1_1errors_1_1ambiguouszoneexception_1_1_ambiguous_zone_exception.html", null ],
      [ "saklient.cloud.errors.cantresizesmallerexception.CantResizeSmallerException", "classsaklient_1_1cloud_1_1errors_1_1cantresizesmallerexception_1_1_cant_resize_smaller_exception.html", null ],
      [ "saklient.cloud.errors.copytoitselfexception.CopyToItselfException", "classsaklient_1_1cloud_1_1errors_1_1copytoitselfexception_1_1_copy_to_itself_exception.html", null ],
      [ "saklient.cloud.errors.dnsaaaarecordnotfoundexception.DnsAaaaRecordNotFoundException", "classsaklient_1_1cloud_1_1errors_1_1dnsaaaarecordnotfoundexception_1_1_dns_aaaa_record_not_found_exception.html", null ],
      [ "saklient.cloud.errors.dnsarecordnotfoundexception.DnsARecordNotFoundException", "classsaklient_1_1cloud_1_1errors_1_1dnsarecordnotfoundexception_1_1_dns_a_record_not_found_exception.html", null ],
      [ "saklient.cloud.errors.filterarraycomparisonexception.FilterArrayComparisonException", "classsaklient_1_1cloud_1_1errors_1_1filterarraycomparisonexception_1_1_filter_array_comparison_exception.html", null ],
      [ "saklient.cloud.errors.filterbadoperatorexception.FilterBadOperatorException", "classsaklient_1_1cloud_1_1errors_1_1filterbadoperatorexception_1_1_filter_bad_operator_exception.html", null ],
      [ "saklient.cloud.errors.filternullcomparisonexception.FilterNullComparisonException", "classsaklient_1_1cloud_1_1errors_1_1filternullcomparisonexception_1_1_filter_null_comparison_exception.html", null ],
      [ "saklient.cloud.errors.filterunknownoperatorexception.FilterUnknownOperatorException", "classsaklient_1_1cloud_1_1errors_1_1filterunknownoperatorexception_1_1_filter_unknown_operator_exception.html", null ],
      [ "saklient.cloud.errors.invalidformatexception.InvalidFormatException", "classsaklient_1_1cloud_1_1errors_1_1invalidformatexception_1_1_invalid_format_exception.html", null ],
      [ "saklient.cloud.errors.invalidparamcombexception.InvalidParamCombException", "classsaklient_1_1cloud_1_1errors_1_1invalidparamcombexception_1_1_invalid_param_comb_exception.html", null ],
      [ "saklient.cloud.errors.invalidrangeexception.InvalidRangeException", "classsaklient_1_1cloud_1_1errors_1_1invalidrangeexception_1_1_invalid_range_exception.html", null ],
      [ "saklient.cloud.errors.missingparamexception.MissingParamException", "classsaklient_1_1cloud_1_1errors_1_1missingparamexception_1_1_missing_param_exception.html", null ],
      [ "saklient.cloud.errors.mustbeofsamezoneexception.MustBeOfSameZoneException", "classsaklient_1_1cloud_1_1errors_1_1mustbeofsamezoneexception_1_1_must_be_of_same_zone_exception.html", null ],
      [ "saklient.cloud.errors.paramipnotfoundexception.ParamIpNotFoundException", "classsaklient_1_1cloud_1_1errors_1_1paramipnotfoundexception_1_1_param_ip_not_found_exception.html", null ],
      [ "saklient.cloud.errors.paramresnotfoundexception.ParamResNotFoundException", "classsaklient_1_1cloud_1_1errors_1_1paramresnotfoundexception_1_1_param_res_not_found_exception.html", null ],
      [ "saklient.cloud.errors.sizemismatchexception.SizeMismatchException", "classsaklient_1_1cloud_1_1errors_1_1sizemismatchexception_1_1_size_mismatch_exception.html", null ],
      [ "saklient.cloud.errors.unsupportedresclassexception.UnsupportedResClassException", "classsaklient_1_1cloud_1_1errors_1_1unsupportedresclassexception_1_1_unsupported_res_class_exception.html", null ]
    ] ],
    [ "HttpConflictException", null, [
      [ "saklient.cloud.errors.archiveisincompleteexception.ArchiveIsIncompleteException", "classsaklient_1_1cloud_1_1errors_1_1archiveisincompleteexception_1_1_archive_is_incomplete_exception.html", null ],
      [ "saklient.cloud.errors.cdromdevicelockedexception.CdromDeviceLockedException", "classsaklient_1_1cloud_1_1errors_1_1cdromdevicelockedexception_1_1_cdrom_device_locked_exception.html", null ],
      [ "saklient.cloud.errors.cdromdisabledexception.CdromDisabledException", "classsaklient_1_1cloud_1_1errors_1_1cdromdisabledexception_1_1_cdrom_disabled_exception.html", null ],
      [ "saklient.cloud.errors.cdrominuseexception.CdromInUseException", "classsaklient_1_1cloud_1_1errors_1_1cdrominuseexception_1_1_cdrom_in_use_exception.html", null ],
      [ "saklient.cloud.errors.cdromisincompleteexception.CdromIsIncompleteException", "classsaklient_1_1cloud_1_1errors_1_1cdromisincompleteexception_1_1_cdrom_is_incomplete_exception.html", null ],
      [ "saklient.cloud.errors.connecttosameswitchexception.ConnectToSameSwitchException", "classsaklient_1_1cloud_1_1errors_1_1connecttosameswitchexception_1_1_connect_to_same_switch_exception.html", null ],
      [ "saklient.cloud.errors.deletediskb4templateexception.DeleteDiskB4TemplateException", "classsaklient_1_1cloud_1_1errors_1_1deletediskb4templateexception_1_1_delete_disk_b4_template_exception.html", null ],
      [ "saklient.cloud.errors.deleteipv6netsfirstexception.DeleteIpV6NetsFirstException", "classsaklient_1_1cloud_1_1errors_1_1deleteipv6netsfirstexception_1_1_delete_ip_v6_nets_first_exception.html", null ],
      [ "saklient.cloud.errors.deleteresb4accountexception.DeleteResB4AccountException", "classsaklient_1_1cloud_1_1errors_1_1deleteresb4accountexception_1_1_delete_res_b4_account_exception.html", null ],
      [ "saklient.cloud.errors.deleterouterb4switchexception.DeleteRouterB4SwitchException", "classsaklient_1_1cloud_1_1errors_1_1deleterouterb4switchexception_1_1_delete_router_b4_switch_exception.html", null ],
      [ "saklient.cloud.errors.deletestaticroutefirstexception.DeleteStaticRouteFirstException", "classsaklient_1_1cloud_1_1errors_1_1deletestaticroutefirstexception_1_1_delete_static_route_first_exception.html", null ],
      [ "saklient.cloud.errors.disconnectb4deleteexception.DisconnectB4DeleteException", "classsaklient_1_1cloud_1_1errors_1_1disconnectb4deleteexception_1_1_disconnect_b4_delete_exception.html", null ],
      [ "saklient.cloud.errors.disconnectb4updateexception.DisconnectB4UpdateException", "classsaklient_1_1cloud_1_1errors_1_1disconnectb4updateexception_1_1_disconnect_b4_update_exception.html", null ],
      [ "saklient.cloud.errors.diskconnectionlimitexception.DiskConnectionLimitException", "classsaklient_1_1cloud_1_1errors_1_1diskconnectionlimitexception_1_1_disk_connection_limit_exception.html", null ],
      [ "saklient.cloud.errors.diskiscopyingexception.DiskIsCopyingException", "classsaklient_1_1cloud_1_1errors_1_1diskiscopyingexception_1_1_disk_is_copying_exception.html", null ],
      [ "saklient.cloud.errors.diskisnotavailableexception.DiskIsNotAvailableException", "classsaklient_1_1cloud_1_1errors_1_1diskisnotavailableexception_1_1_disk_is_not_available_exception.html", null ],
      [ "saklient.cloud.errors.disklicensemismatchexception.DiskLicenseMismatchException", "classsaklient_1_1cloud_1_1errors_1_1disklicensemismatchexception_1_1_disk_license_mismatch_exception.html", null ],
      [ "saklient.cloud.errors.diskorssinmigrationexception.DiskOrSsInMigrationException", "classsaklient_1_1cloud_1_1errors_1_1diskorssinmigrationexception_1_1_disk_or_ss_in_migration_exception.html", null ],
      [ "saklient.cloud.errors.duplicateaccountcodeexception.DuplicateAccountCodeException", "classsaklient_1_1cloud_1_1errors_1_1duplicateaccountcodeexception_1_1_duplicate_account_code_exception.html", null ],
      [ "saklient.cloud.errors.duplicateentryexception.DuplicateEntryException", "classsaklient_1_1cloud_1_1errors_1_1duplicateentryexception_1_1_duplicate_entry_exception.html", null ],
      [ "saklient.cloud.errors.duplicateusercodeexception.DuplicateUserCodeException", "classsaklient_1_1cloud_1_1errors_1_1duplicateusercodeexception_1_1_duplicate_user_code_exception.html", null ],
      [ "saklient.cloud.errors.filenotuploadedexception.FileNotUploadedException", "classsaklient_1_1cloud_1_1errors_1_1filenotuploadedexception_1_1_file_not_uploaded_exception.html", null ],
      [ "saklient.cloud.errors.ftpcannotcloseexception.FtpCannotCloseException", "classsaklient_1_1cloud_1_1errors_1_1ftpcannotcloseexception_1_1_ftp_cannot_close_exception.html", null ],
      [ "saklient.cloud.errors.ftpisalreadycloseexception.FtpIsAlreadyCloseException", "classsaklient_1_1cloud_1_1errors_1_1ftpisalreadycloseexception_1_1_ftp_is_already_close_exception.html", null ],
      [ "saklient.cloud.errors.ftpisalreadyopenexception.FtpIsAlreadyOpenException", "classsaklient_1_1cloud_1_1errors_1_1ftpisalreadyopenexception_1_1_ftp_is_already_open_exception.html", null ],
      [ "saklient.cloud.errors.ftpmustbeclosedexception.FtpMustBeClosedException", "classsaklient_1_1cloud_1_1errors_1_1ftpmustbeclosedexception_1_1_ftp_must_be_closed_exception.html", null ],
      [ "saklient.cloud.errors.illegaldasusageexception.IllegalDasUsageException", "classsaklient_1_1cloud_1_1errors_1_1illegaldasusageexception_1_1_illegal_das_usage_exception.html", null ],
      [ "saklient.cloud.errors.inmigrationexception.InMigrationException", "classsaklient_1_1cloud_1_1errors_1_1inmigrationexception_1_1_in_migration_exception.html", null ],
      [ "saklient.cloud.errors.ipv6netalreadyattachedexception.IpV6NetAlreadyAttachedException", "classsaklient_1_1cloud_1_1errors_1_1ipv6netalreadyattachedexception_1_1_ip_v6_net_already_attached_exception.html", null ],
      [ "saklient.cloud.errors.limitcountinaccountexception.LimitCountInAccountException", "classsaklient_1_1cloud_1_1errors_1_1limitcountinaccountexception_1_1_limit_count_in_account_exception.html", null ],
      [ "saklient.cloud.errors.limitcountinmemberexception.LimitCountInMemberException", "classsaklient_1_1cloud_1_1errors_1_1limitcountinmemberexception_1_1_limit_count_in_member_exception.html", null ],
      [ "saklient.cloud.errors.limitcountinnetworkexception.LimitCountInNetworkException", "classsaklient_1_1cloud_1_1errors_1_1limitcountinnetworkexception_1_1_limit_count_in_network_exception.html", null ],
      [ "saklient.cloud.errors.limitcountinrouterexception.LimitCountInRouterException", "classsaklient_1_1cloud_1_1errors_1_1limitcountinrouterexception_1_1_limit_count_in_router_exception.html", null ],
      [ "saklient.cloud.errors.limitcountinzoneexception.LimitCountInZoneException", "classsaklient_1_1cloud_1_1errors_1_1limitcountinzoneexception_1_1_limit_count_in_zone_exception.html", null ],
      [ "saklient.cloud.errors.limitmemoryinaccountexception.LimitMemoryInAccountException", "classsaklient_1_1cloud_1_1errors_1_1limitmemoryinaccountexception_1_1_limit_memory_in_account_exception.html", null ],
      [ "saklient.cloud.errors.limitsizeinaccountexception.LimitSizeInAccountException", "classsaklient_1_1cloud_1_1errors_1_1limitsizeinaccountexception_1_1_limit_size_in_account_exception.html", null ],
      [ "saklient.cloud.errors.missingisoimageexception.MissingIsoImageException", "classsaklient_1_1cloud_1_1errors_1_1missingisoimageexception_1_1_missing_iso_image_exception.html", null ],
      [ "saklient.cloud.errors.notforrouterexception.NotForRouterException", "classsaklient_1_1cloud_1_1errors_1_1notforrouterexception_1_1_not_for_router_exception.html", null ],
      [ "saklient.cloud.errors.notreplicatingexception.NotReplicatingException", "classsaklient_1_1cloud_1_1errors_1_1notreplicatingexception_1_1_not_replicating_exception.html", null ],
      [ "saklient.cloud.errors.notwithhybridconnexception.NotWithHybridconnException", "classsaklient_1_1cloud_1_1errors_1_1notwithhybridconnexception_1_1_not_with_hybridconn_exception.html", null ],
      [ "saklient.cloud.errors.oldstorageplanexception.OldStoragePlanException", "classsaklient_1_1cloud_1_1errors_1_1oldstorageplanexception_1_1_old_storage_plan_exception.html", null ],
      [ "saklient.cloud.errors.originalhashmismatchexception.OriginalHashMismatchException", "classsaklient_1_1cloud_1_1errors_1_1originalhashmismatchexception_1_1_original_hash_mismatch_exception.html", null ],
      [ "saklient.cloud.errors.packetfilterapplyingexception.PacketFilterApplyingException", "classsaklient_1_1cloud_1_1errors_1_1packetfilterapplyingexception_1_1_packet_filter_applying_exception.html", null ],
      [ "saklient.cloud.errors.packetfilterversionmismatchexception.PacketFilterVersionMismatchException", "classsaklient_1_1cloud_1_1errors_1_1packetfilterversionmismatchexception_1_1_packet_filter_version_mismatch_exception.html", null ],
      [ "saklient.cloud.errors.replicaalreadyexistsexception.ReplicaAlreadyExistsException", "classsaklient_1_1cloud_1_1errors_1_1replicaalreadyexistsexception_1_1_replica_already_exists_exception.html", null ],
      [ "saklient.cloud.errors.resalreadyconnectedexception.ResAlreadyConnectedException", "classsaklient_1_1cloud_1_1errors_1_1resalreadyconnectedexception_1_1_res_already_connected_exception.html", null ],
      [ "saklient.cloud.errors.resalreadydisconnectedexception.ResAlreadyDisconnectedException", "classsaklient_1_1cloud_1_1errors_1_1resalreadydisconnectedexception_1_1_res_already_disconnected_exception.html", null ],
      [ "saklient.cloud.errors.resalreadyexistsexception.ResAlreadyExistsException", "classsaklient_1_1cloud_1_1errors_1_1resalreadyexistsexception_1_1_res_already_exists_exception.html", null ],
      [ "saklient.cloud.errors.resusedinzoneexception.ResUsedInZoneException", "classsaklient_1_1cloud_1_1errors_1_1resusedinzoneexception_1_1_res_used_in_zone_exception.html", null ],
      [ "saklient.cloud.errors.runoutofipaddressexception.RunOutOfIpAddressException", "classsaklient_1_1cloud_1_1errors_1_1runoutofipaddressexception_1_1_run_out_of_ip_address_exception.html", null ],
      [ "saklient.cloud.errors.samelicenserequiredexception.SameLicenseRequiredException", "classsaklient_1_1cloud_1_1errors_1_1samelicenserequiredexception_1_1_same_license_required_exception.html", null ],
      [ "saklient.cloud.errors.serveriscleaningexception.ServerIsCleaningException", "classsaklient_1_1cloud_1_1errors_1_1serveriscleaningexception_1_1_server_is_cleaning_exception.html", null ],
      [ "saklient.cloud.errors.serverpowermustbedownexception.ServerPowerMustBeDownException", "classsaklient_1_1cloud_1_1errors_1_1serverpowermustbedownexception_1_1_server_power_must_be_down_exception.html", null ],
      [ "saklient.cloud.errors.serverpowermustbeupexception.ServerPowerMustBeUpException", "classsaklient_1_1cloud_1_1errors_1_1serverpowermustbeupexception_1_1_server_power_must_be_up_exception.html", null ],
      [ "saklient.cloud.errors.snapshotinmigrationexception.SnapshotInMigrationException", "classsaklient_1_1cloud_1_1errors_1_1snapshotinmigrationexception_1_1_snapshot_in_migration_exception.html", null ],
      [ "saklient.cloud.errors.stillcreatingexception.StillCreatingException", "classsaklient_1_1cloud_1_1errors_1_1stillcreatingexception_1_1_still_creating_exception.html", null ],
      [ "saklient.cloud.errors.switchhybridconnectedexception.SwitchHybridConnectedException", "classsaklient_1_1cloud_1_1errors_1_1switchhybridconnectedexception_1_1_switch_hybrid_connected_exception.html", null ],
      [ "saklient.cloud.errors.templateftpisopenexception.TemplateFtpIsOpenException", "classsaklient_1_1cloud_1_1errors_1_1templateftpisopenexception_1_1_template_ftp_is_open_exception.html", null ],
      [ "saklient.cloud.errors.templateisincompleteexception.TemplateIsIncompleteException", "classsaklient_1_1cloud_1_1errors_1_1templateisincompleteexception_1_1_template_is_incomplete_exception.html", null ]
    ] ],
    [ "HttpException", null, [
      [ "saklient.errors.httpbadgatewayexception.HttpBadGatewayException", "classsaklient_1_1errors_1_1httpbadgatewayexception_1_1_http_bad_gateway_exception.html", null ],
      [ "saklient.errors.httpbadrequestexception.HttpBadRequestException", "classsaklient_1_1errors_1_1httpbadrequestexception_1_1_http_bad_request_exception.html", null ],
      [ "saklient.errors.httpconflictexception.HttpConflictException", "classsaklient_1_1errors_1_1httpconflictexception_1_1_http_conflict_exception.html", null ],
      [ "saklient.errors.httpexpectationfailedexception.HttpExpectationFailedException", "classsaklient_1_1errors_1_1httpexpectationfailedexception_1_1_http_expectation_failed_exception.html", null ],
      [ "saklient.errors.httpfaileddependencyexception.HttpFailedDependencyException", "classsaklient_1_1errors_1_1httpfaileddependencyexception_1_1_http_failed_dependency_exception.html", null ],
      [ "saklient.errors.httpforbiddenexception.HttpForbiddenException", "classsaklient_1_1errors_1_1httpforbiddenexception_1_1_http_forbidden_exception.html", null ],
      [ "saklient.errors.httpgatewaytimeoutexception.HttpGatewayTimeoutException", "classsaklient_1_1errors_1_1httpgatewaytimeoutexception_1_1_http_gateway_timeout_exception.html", null ],
      [ "saklient.errors.httpgoneexception.HttpGoneException", "classsaklient_1_1errors_1_1httpgoneexception_1_1_http_gone_exception.html", null ],
      [ "saklient.errors.httphttpversionnotsupportedexception.HttpHttpVersionNotSupportedException", "classsaklient_1_1errors_1_1httphttpversionnotsupportedexception_1_1_http_http_version_not_supported_exception.html", null ],
      [ "saklient.errors.httpinsufficientstorageexception.HttpInsufficientStorageException", "classsaklient_1_1errors_1_1httpinsufficientstorageexception_1_1_http_insufficient_storage_exception.html", null ],
      [ "saklient.errors.httpinternalservererrorexception.HttpInternalServerErrorException", "classsaklient_1_1errors_1_1httpinternalservererrorexception_1_1_http_internal_server_error_exception.html", null ],
      [ "saklient.errors.httplengthrequiredexception.HttpLengthRequiredException", "classsaklient_1_1errors_1_1httplengthrequiredexception_1_1_http_length_required_exception.html", null ],
      [ "saklient.errors.httplockedexception.HttpLockedException", "classsaklient_1_1errors_1_1httplockedexception_1_1_http_locked_exception.html", null ],
      [ "saklient.errors.httpmethodnotallowedexception.HttpMethodNotAllowedException", "classsaklient_1_1errors_1_1httpmethodnotallowedexception_1_1_http_method_not_allowed_exception.html", null ],
      [ "saklient.errors.httpnotacceptableexception.HttpNotAcceptableException", "classsaklient_1_1errors_1_1httpnotacceptableexception_1_1_http_not_acceptable_exception.html", null ],
      [ "saklient.errors.httpnotextendedexception.HttpNotExtendedException", "classsaklient_1_1errors_1_1httpnotextendedexception_1_1_http_not_extended_exception.html", null ],
      [ "saklient.errors.httpnotfoundexception.HttpNotFoundException", "classsaklient_1_1errors_1_1httpnotfoundexception_1_1_http_not_found_exception.html", null ],
      [ "saklient.errors.httpnotimplementedexception.HttpNotImplementedException", "classsaklient_1_1errors_1_1httpnotimplementedexception_1_1_http_not_implemented_exception.html", null ],
      [ "saklient.errors.httppaymentrequiredexception.HttpPaymentRequiredException", "classsaklient_1_1errors_1_1httppaymentrequiredexception_1_1_http_payment_required_exception.html", null ],
      [ "saklient.errors.httppreconditionfailedexception.HttpPreconditionFailedException", "classsaklient_1_1errors_1_1httppreconditionfailedexception_1_1_http_precondition_failed_exception.html", null ],
      [ "saklient.errors.httpproxyauthenticationrequiredexception.HttpProxyAuthenticationRequiredException", "classsaklient_1_1errors_1_1httpproxyauthenticationrequiredexception_1_1_http_proxy_authentication_required_exception.html", null ],
      [ "saklient.errors.httprequestedrangenotsatisfiableexception.HttpRequestedRangeNotSatisfiableException", "classsaklient_1_1errors_1_1httprequestedrangenotsatisfiableexception_1_1_http_requested_range_not_satisfiable_exception.html", null ],
      [ "saklient.errors.httprequestentitytoolargeexception.HttpRequestEntityTooLargeException", "classsaklient_1_1errors_1_1httprequestentitytoolargeexception_1_1_http_request_entity_too_large_exception.html", null ],
      [ "saklient.errors.httprequesttimeoutexception.HttpRequestTimeoutException", "classsaklient_1_1errors_1_1httprequesttimeoutexception_1_1_http_request_timeout_exception.html", null ],
      [ "saklient.errors.httprequesturitoolongexception.HttpRequestUriTooLongException", "classsaklient_1_1errors_1_1httprequesturitoolongexception_1_1_http_request_uri_too_long_exception.html", null ],
      [ "saklient.errors.httpserviceunavailableexception.HttpServiceUnavailableException", "classsaklient_1_1errors_1_1httpserviceunavailableexception_1_1_http_service_unavailable_exception.html", null ],
      [ "saklient.errors.httpunauthorizedexception.HttpUnauthorizedException", "classsaklient_1_1errors_1_1httpunauthorizedexception_1_1_http_unauthorized_exception.html", null ],
      [ "saklient.errors.httpunprocessableentityexception.HttpUnprocessableEntityException", "classsaklient_1_1errors_1_1httpunprocessableentityexception_1_1_http_unprocessable_entity_exception.html", null ],
      [ "saklient.errors.httpunsupportedmediatypeexception.HttpUnsupportedMediaTypeException", "classsaklient_1_1errors_1_1httpunsupportedmediatypeexception_1_1_http_unsupported_media_type_exception.html", null ],
      [ "saklient.errors.httpupgraderequiredexception.HttpUpgradeRequiredException", "classsaklient_1_1errors_1_1httpupgraderequiredexception_1_1_http_upgrade_required_exception.html", null ],
      [ "saklient.errors.httpvariantalsonegotiatesexception.HttpVariantAlsoNegotiatesException", "classsaklient_1_1errors_1_1httpvariantalsonegotiatesexception_1_1_http_variant_also_negotiates_exception.html", null ]
    ] ],
    [ "HttpForbiddenException", null, [
      [ "saklient.cloud.errors.accessapikeydisabledexception.AccessApiKeyDisabledException", "classsaklient_1_1cloud_1_1errors_1_1accessapikeydisabledexception_1_1_access_api_key_disabled_exception.html", null ],
      [ "saklient.cloud.errors.accesssakuraexception.AccessSakuraException", "classsaklient_1_1cloud_1_1errors_1_1accesssakuraexception_1_1_access_sakura_exception.html", null ],
      [ "saklient.cloud.errors.accessstaffexception.AccessStaffException", "classsaklient_1_1cloud_1_1errors_1_1accessstaffexception_1_1_access_staff_exception.html", null ],
      [ "saklient.cloud.errors.accesstokenexception.AccessTokenException", "classsaklient_1_1cloud_1_1errors_1_1accesstokenexception_1_1_access_token_exception.html", null ],
      [ "saklient.cloud.errors.accessxhrorapikeyexception.AccessXhrOrApiKeyException", "classsaklient_1_1cloud_1_1errors_1_1accessxhrorapikeyexception_1_1_access_xhr_or_api_key_exception.html", null ],
      [ "saklient.cloud.errors.accountnotspecifiedexception.AccountNotSpecifiedException", "classsaklient_1_1cloud_1_1errors_1_1accountnotspecifiedexception_1_1_account_not_specified_exception.html", null ],
      [ "saklient.cloud.errors.disabledinsandboxexception.DisabledInSandboxException", "classsaklient_1_1cloud_1_1errors_1_1disabledinsandboxexception_1_1_disabled_in_sandbox_exception.html", null ],
      [ "saklient.cloud.errors.dontcreateinsandboxexception.DontCreateInSandboxException", "classsaklient_1_1cloud_1_1errors_1_1dontcreateinsandboxexception_1_1_dont_create_in_sandbox_exception.html", null ],
      [ "saklient.cloud.errors.usernotspecifiedexception.UserNotSpecifiedException", "classsaklient_1_1cloud_1_1errors_1_1usernotspecifiedexception_1_1_user_not_specified_exception.html", null ]
    ] ],
    [ "HttpGatewayTimeoutException", null, [
      [ "saklient.cloud.errors.apiproxytimeoutexception.ApiProxyTimeoutException", "classsaklient_1_1cloud_1_1errors_1_1apiproxytimeoutexception_1_1_api_proxy_timeout_exception.html", null ],
      [ "saklient.cloud.errors.apiproxytimeoutnongetexception.ApiProxyTimeoutNonGetException", "classsaklient_1_1cloud_1_1errors_1_1apiproxytimeoutnongetexception_1_1_api_proxy_timeout_non_get_exception.html", null ]
    ] ],
    [ "HttpInternalServerErrorException", null, [
      [ "saklient.cloud.errors.unknownexception.UnknownException", "classsaklient_1_1cloud_1_1errors_1_1unknownexception_1_1_unknown_exception.html", null ]
    ] ],
    [ "HttpNotFoundException", null, [
      [ "saklient.cloud.errors.ambiguousidentifierexception.AmbiguousIdentifierException", "classsaklient_1_1cloud_1_1errors_1_1ambiguousidentifierexception_1_1_ambiguous_identifier_exception.html", null ],
      [ "saklient.cloud.errors.invaliduriargumentexception.InvalidUriArgumentException", "classsaklient_1_1cloud_1_1errors_1_1invaliduriargumentexception_1_1_invalid_uri_argument_exception.html", null ],
      [ "saklient.cloud.errors.replicanotfoundexception.ReplicaNotFoundException", "classsaklient_1_1cloud_1_1errors_1_1replicanotfoundexception_1_1_replica_not_found_exception.html", null ],
      [ "saklient.cloud.errors.resourcepathnotfoundexception.ResourcePathNotFoundException", "classsaklient_1_1cloud_1_1errors_1_1resourcepathnotfoundexception_1_1_resource_path_not_found_exception.html", null ]
    ] ],
    [ "HttpPaymentRequiredException", null, [
      [ "saklient.cloud.errors.paymentcreditcardexception.PaymentCreditCardException", "classsaklient_1_1cloud_1_1errors_1_1paymentcreditcardexception_1_1_payment_credit_card_exception.html", null ],
      [ "saklient.cloud.errors.paymentpaymentexception.PaymentPaymentException", "classsaklient_1_1cloud_1_1errors_1_1paymentpaymentexception_1_1_payment_payment_exception.html", null ],
      [ "saklient.cloud.errors.paymentregistrationexception.PaymentRegistrationException", "classsaklient_1_1cloud_1_1errors_1_1paymentregistrationexception_1_1_payment_registration_exception.html", null ],
      [ "saklient.cloud.errors.paymenttelcertificationexception.PaymentTelCertificationException", "classsaklient_1_1cloud_1_1errors_1_1paymenttelcertificationexception_1_1_payment_tel_certification_exception.html", null ],
      [ "saklient.cloud.errors.paymentunpayableexception.PaymentUnpayableException", "classsaklient_1_1cloud_1_1errors_1_1paymentunpayableexception_1_1_payment_unpayable_exception.html", null ],
      [ "saklient.cloud.errors.penaltyoperationexception.PenaltyOperationException", "classsaklient_1_1cloud_1_1errors_1_1penaltyoperationexception_1_1_penalty_operation_exception.html", null ]
    ] ],
    [ "HttpServiceUnavailableException", null, [
      [ "saklient.cloud.errors.bootfailurebylockexception.BootFailureByLockException", "classsaklient_1_1cloud_1_1errors_1_1bootfailurebylockexception_1_1_boot_failure_by_lock_exception.html", null ],
      [ "saklient.cloud.errors.bootfailureingroupexception.BootFailureInGroupException", "classsaklient_1_1cloud_1_1errors_1_1bootfailureingroupexception_1_1_boot_failure_in_group_exception.html", null ],
      [ "saklient.cloud.errors.busyexception.BusyException", "classsaklient_1_1cloud_1_1errors_1_1busyexception_1_1_busy_exception.html", null ],
      [ "saklient.cloud.errors.contractcreationexception.ContractCreationException", "classsaklient_1_1cloud_1_1errors_1_1contractcreationexception_1_1_contract_creation_exception.html", null ],
      [ "saklient.cloud.errors.diskstockrunoutexception.DiskStockRunOutException", "classsaklient_1_1cloud_1_1errors_1_1diskstockrunoutexception_1_1_disk_stock_run_out_exception.html", null ],
      [ "saklient.cloud.errors.dnsptrupdatefailureexception.DnsPtrUpdateFailureException", "classsaklient_1_1cloud_1_1errors_1_1dnsptrupdatefailureexception_1_1_dns_ptr_update_failure_exception.html", null ],
      [ "saklient.cloud.errors.hostoperationfailureexception.HostOperationFailureException", "classsaklient_1_1cloud_1_1errors_1_1hostoperationfailureexception_1_1_host_operation_failure_exception.html", null ],
      [ "saklient.cloud.errors.nodisplayresponseexception.NoDisplayResponseException", "classsaklient_1_1cloud_1_1errors_1_1nodisplayresponseexception_1_1_no_display_response_exception.html", null ],
      [ "saklient.cloud.errors.operationfailureexception.OperationFailureException", "classsaklient_1_1cloud_1_1errors_1_1operationfailureexception_1_1_operation_failure_exception.html", null ],
      [ "saklient.cloud.errors.operationtimeoutexception.OperationTimeoutException", "classsaklient_1_1cloud_1_1errors_1_1operationtimeoutexception_1_1_operation_timeout_exception.html", null ],
      [ "saklient.cloud.errors.servercouldnotstopexception.ServerCouldNotStopException", "classsaklient_1_1cloud_1_1errors_1_1servercouldnotstopexception_1_1_server_could_not_stop_exception.html", null ],
      [ "saklient.cloud.errors.serveroperationfailureexception.ServerOperationFailureException", "classsaklient_1_1cloud_1_1errors_1_1serveroperationfailureexception_1_1_server_operation_failure_exception.html", null ],
      [ "saklient.cloud.errors.servicetemporarilyunavailableexception.ServiceTemporarilyUnavailableException", "classsaklient_1_1cloud_1_1errors_1_1servicetemporarilyunavailableexception_1_1_service_temporarily_unavailable_exception.html", null ],
      [ "saklient.cloud.errors.storageabnormalexception.StorageAbnormalException", "classsaklient_1_1cloud_1_1errors_1_1storageabnormalexception_1_1_storage_abnormal_exception.html", null ],
      [ "saklient.cloud.errors.storageoperationfailureexception.StorageOperationFailureException", "classsaklient_1_1cloud_1_1errors_1_1storageoperationfailureexception_1_1_storage_operation_failure_exception.html", null ],
      [ "saklient.cloud.errors.toomanyrequestexception.TooManyRequestException", "classsaklient_1_1cloud_1_1errors_1_1toomanyrequestexception_1_1_too_many_request_exception.html", null ],
      [ "saklient.cloud.errors.unknownostypeexception.UnknownOsTypeException", "classsaklient_1_1cloud_1_1errors_1_1unknownostypeexception_1_1_unknown_os_type_exception.html", null ],
      [ "saklient.cloud.errors.vncproxyrequestfailureexception.VncProxyRequestFailureException", "classsaklient_1_1cloud_1_1errors_1_1vncproxyrequestfailureexception_1_1_vnc_proxy_request_failure_exception.html", null ]
    ] ],
    [ "Model", null, [
      [ "saklient.cloud.models.model_appliance.Model_Appliance", "classsaklient_1_1cloud_1_1models_1_1model__appliance_1_1_model___appliance.html", null ],
      [ "saklient.cloud.models.model_archive.Model_Archive", "classsaklient_1_1cloud_1_1models_1_1model__archive_1_1_model___archive.html", null ],
      [ "saklient.cloud.models.model_bridge.Model_Bridge", "classsaklient_1_1cloud_1_1models_1_1model__bridge_1_1_model___bridge.html", null ],
      [ "saklient.cloud.models.model_disk.Model_Disk", "classsaklient_1_1cloud_1_1models_1_1model__disk_1_1_model___disk.html", null ],
      [ "saklient.cloud.models.model_diskplan.Model_DiskPlan", "classsaklient_1_1cloud_1_1models_1_1model__diskplan_1_1_model___disk_plan.html", null ],
      [ "saklient.cloud.models.model_icon.Model_Icon", "classsaklient_1_1cloud_1_1models_1_1model__icon_1_1_model___icon.html", null ],
      [ "saklient.cloud.models.model_iface.Model_Iface", "classsaklient_1_1cloud_1_1models_1_1model__iface_1_1_model___iface.html", null ],
      [ "saklient.cloud.models.model_ipv6net.Model_Ipv6Net", "classsaklient_1_1cloud_1_1models_1_1model__ipv6net_1_1_model___ipv6_net.html", null ],
      [ "saklient.cloud.models.model_isoimage.Model_IsoImage", "classsaklient_1_1cloud_1_1models_1_1model__isoimage_1_1_model___iso_image.html", null ],
      [ "saklient.cloud.models.model_license.Model_License", "classsaklient_1_1cloud_1_1models_1_1model__license_1_1_model___license.html", null ],
      [ "saklient.cloud.models.model_licenseinfo.Model_LicenseInfo", "classsaklient_1_1cloud_1_1models_1_1model__licenseinfo_1_1_model___license_info.html", null ],
      [ "saklient.cloud.models.model_region.Model_Region", "classsaklient_1_1cloud_1_1models_1_1model__region_1_1_model___region.html", null ],
      [ "saklient.cloud.models.model_router.Model_Router", "classsaklient_1_1cloud_1_1models_1_1model__router_1_1_model___router.html", null ],
      [ "saklient.cloud.models.model_routerplan.Model_RouterPlan", "classsaklient_1_1cloud_1_1models_1_1model__routerplan_1_1_model___router_plan.html", null ],
      [ "saklient.cloud.models.model_script.Model_Script", "classsaklient_1_1cloud_1_1models_1_1model__script_1_1_model___script.html", null ],
      [ "saklient.cloud.models.model_server.Model_Server", "classsaklient_1_1cloud_1_1models_1_1model__server_1_1_model___server.html", null ],
      [ "saklient.cloud.models.model_serverplan.Model_ServerPlan", "classsaklient_1_1cloud_1_1models_1_1model__serverplan_1_1_model___server_plan.html", null ],
      [ "saklient.cloud.models.model_swytch.Model_Swytch", "classsaklient_1_1cloud_1_1models_1_1model__swytch_1_1_model___swytch.html", null ]
    ] ],
    [ "Resource", null, [
      [ "saklient.cloud.resources.appliance.Appliance", "classsaklient_1_1cloud_1_1resources_1_1appliance_1_1_appliance.html", null ],
      [ "saklient.cloud.resources.archive.Archive", "classsaklient_1_1cloud_1_1resources_1_1archive_1_1_archive.html", null ],
      [ "saklient.cloud.resources.bridge.Bridge", "classsaklient_1_1cloud_1_1resources_1_1bridge_1_1_bridge.html", null ],
      [ "saklient.cloud.resources.disk.Disk", "classsaklient_1_1cloud_1_1resources_1_1disk_1_1_disk.html", null ],
      [ "saklient.cloud.resources.diskplan.DiskPlan", "classsaklient_1_1cloud_1_1resources_1_1diskplan_1_1_disk_plan.html", null ],
      [ "saklient.cloud.resources.icon.Icon", "classsaklient_1_1cloud_1_1resources_1_1icon_1_1_icon.html", null ],
      [ "saklient.cloud.resources.iface.Iface", "classsaklient_1_1cloud_1_1resources_1_1iface_1_1_iface.html", null ],
      [ "saklient.cloud.resources.ipv4net.Ipv4Net", "classsaklient_1_1cloud_1_1resources_1_1ipv4net_1_1_ipv4_net.html", null ],
      [ "saklient.cloud.resources.ipv6net.Ipv6Net", "classsaklient_1_1cloud_1_1resources_1_1ipv6net_1_1_ipv6_net.html", null ],
      [ "saklient.cloud.resources.isoimage.IsoImage", "classsaklient_1_1cloud_1_1resources_1_1isoimage_1_1_iso_image.html", null ],
      [ "saklient.cloud.resources.license.License", "classsaklient_1_1cloud_1_1resources_1_1license_1_1_license.html", null ],
      [ "saklient.cloud.resources.licenseinfo.LicenseInfo", "classsaklient_1_1cloud_1_1resources_1_1licenseinfo_1_1_license_info.html", null ],
      [ "saklient.cloud.resources.region.Region", "classsaklient_1_1cloud_1_1resources_1_1region_1_1_region.html", null ],
      [ "saklient.cloud.resources.router.Router", "classsaklient_1_1cloud_1_1resources_1_1router_1_1_router.html", null ],
      [ "saklient.cloud.resources.routerplan.RouterPlan", "classsaklient_1_1cloud_1_1resources_1_1routerplan_1_1_router_plan.html", null ],
      [ "saklient.cloud.resources.script.Script", "classsaklient_1_1cloud_1_1resources_1_1script_1_1_script.html", null ],
      [ "saklient.cloud.resources.server.Server", "classsaklient_1_1cloud_1_1resources_1_1server_1_1_server.html", null ],
      [ "saklient.cloud.resources.serverinstance.ServerInstance", "classsaklient_1_1cloud_1_1resources_1_1serverinstance_1_1_server_instance.html", null ],
      [ "saklient.cloud.resources.serverplan.ServerPlan", "classsaklient_1_1cloud_1_1resources_1_1serverplan_1_1_server_plan.html", null ],
      [ "saklient.cloud.resources.swytch.Swytch", "classsaklient_1_1cloud_1_1resources_1_1swytch_1_1_swytch.html", null ]
    ] ]
];